steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/new-grad-ten-years-experience:base || exit 0
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/base.Dockerfile',
    '-t', 'new-grad-ten-years-experience:base',
    '-t', 'gcr.io/$PROJECT_ID/new-grad-ten-years-experience:base',
    '--cache-from', 'gcr.io/$PROJECT_ID/new-grad-ten-years-experience:base',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/new-grad-ten-years-experience:base']
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/Dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/new-grad-ten-years-experience:latest',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/coverage.Dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/new-grad-ten-years-experience:coverage',
    '.'
  ]
images: ['gcr.io/$PROJECT_ID/new-grad-ten-years-experience:base', 'gcr.io/$PROJECT_ID/new-grad-ten-years-experience:coverage', 'gcr.io/$PROJECT_ID/new-grad-ten-years-experience:latest']
